# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 30 Mar 2016 14:32:01 +0000
*               @ALL          0
*               @user         8
