<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jonathan
 * Date: Wed, 30 Mar 2016 16:12:30 +0100
 */

$conf['title'] = 'Nube Hilados :: Manual de Procedimientos';
$conf['lang'] = 'es';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
